"""Mac で最適化したパラメータを Windows の EA に渡すためのファイルを書き出す。

2種類を出力する:
- <name>.set : MT5 の「パラメータ読み込み」で使うプリセット（UTF-16LE）
- <name>.txt : EA が定期的に読み直す key=value ファイル。
               MT5 の データフォルダ/../Common/Files/ に置く（EA は FILE_COMMON で読む）

キー名は EA の input 変数名と同じ（例: dc_entry_period, ex_trail_atr, rk_risk_per_trade）。
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .backtest import BacktestConfig, Sleeve
from .instruments import Instrument

# EA の ENUM_CFD_STRATEGY と同じ順番
EA_STRATEGIES = ["donchian", "squeeze", "pullback", "reversion"]
EA_CLUSTER_IDS = {"energy": 1, "metals": 2}


def ea_params(sleeve: Sleeve, inst: Instrument, config: BacktestConfig,
              timeframe_minutes: int | None = None) -> dict[str, Any]:
    strat = sleeve.strategy
    if strat.name not in EA_STRATEGIES:
        raise NotImplementedError(f"戦略 '{strat.name}' は EA 未対応（{EA_STRATEGIES} のみ）")
    exit_cfg = sleeve.exit_config(config.exit)
    rc, fc = config.risk, config.filters
    out: dict[str, Any] = {"strategy": strat.name}
    for k, v in strat.params.items():
        out[f"{strat.ea_prefix}_{k}"] = v
    for k, v in exit_cfg.to_dict().items():
        out[f"ex_{k}"] = v
    out.update({
        "rk_risk_per_trade": round(rc.risk_per_trade * sleeve.risk_weight, 6),
        "rk_max_total_risk": rc.max_total_risk,
        "rk_cluster_id": EA_CLUSTER_IDS.get(inst.cluster, 0),
        "rk_cluster_max_risk": rc.cluster_max_risk.get(inst.cluster, rc.max_total_risk),
        "rk_max_positions_per_symbol": rc.max_positions_per_symbol,
        "rk_daily_loss_limit": rc.daily_loss_limit,
        "rk_max_drawdown_halt": rc.max_drawdown_halt,
        "rk_max_margin_utilization": rc.max_margin_utilization,
        "rk_max_leverage_symbol": rc.max_leverage_symbol,
        "rk_max_leverage_total": rc.max_leverage_total,
        "rk_min_lot_overshoot": rc.min_lot_overshoot,
        "ft_oil_events": fc.oil_events and "oil" in inst.event_tags,
        "ft_event_tags": ",".join(inst.event_tags),
        "ft_event_block_before_min": int(fc.event_block_before.total_seconds() // 60),
        "ft_event_block_after_min": int(fc.event_block_after.total_seconds() // 60),
        "ft_no_entry_after_fri_et": -1.0 if fc.no_entry_after_fri_et is None else fc.no_entry_after_fri_et,
        "ft_weekend_flatten_fri_et": fc.weekend_flatten_fri_et,
        "ft_max_spread_points": round(inst.spread * fc.max_spread_mult / inst.point_size),
    })
    if timeframe_minutes:
        out["ea_timeframe_minutes"] = int(timeframe_minutes)  # 違う時間足のチャートでは EA が起動しない
    return out


def _fmt(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, float):
        return f"{v:.10g}"
    return str(v)


def write_param_txt(params: dict[str, Any], path: str | Path) -> Path:
    path = Path(path)
    lines = ["# cfdbot EA parameters (key=value). Generated by cfdbot.export"]
    lines += [f"{k}={_fmt(v)}" for k, v in params.items()]
    path.write_text("\n".join(lines) + "\n", encoding="ascii")
    return path


def write_set_file(params: dict[str, Any], path: str | Path) -> Path:
    path = Path(path)
    lines = []
    for k, v in params.items():
        if k == "strategy":
            v = EA_STRATEGIES.index(v)
        lines.append(f"{k}={_fmt(v)}")
    path.write_bytes(("\r\n".join(lines) + "\r\n").encode("utf-16"))  # BOM 付き UTF-16LE
    return path


def export_sleeve(
    sleeve: Sleeve, inst: Instrument, config: BacktestConfig, out_dir: str | Path,
    timeframe_minutes: int | None = None,
) -> tuple[Path, Path]:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    params = ea_params(sleeve, inst, config, timeframe_minutes)
    base = f"cfdbot_{inst.symbol}_{sleeve.strategy.name}"
    return (
        write_set_file(params, out_dir / f"{base}.set"),
        write_param_txt(params, out_dir / f"{base}.txt"),
    )
